// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stczxksirrvukzujhhrd.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Y3p4a3NpcnJ2dWt6dWpoaHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDU0NTcsImV4cCI6MjA1NzI4MTQ1N30.jV2KVOb6h-_0Tpf-zs723QE9_kVgcgddgrLahzMYO-w";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
